UI voor het toevoegen van Genre's
NicoVermeir/Fletnix pull request #9
Opened 2019-11-18 21:01 UTC by tdehaes

2019-11-19 15:20 UTC, NicoVermeir requested changes

2019-11-19 15:20 UTC, NicoVermeir commented on Fletnix.Repositories/GenreRepository.cs
> +
Overbodige whitespace verwijderen

2019-11-19 15:20 UTC, NicoVermeir commented on Fletnix.Repositories/GenreRepository.cs
> +
overbodige whitespace

2019-11-19 15:20 UTC, NicoVermeir commented on Fletnix.Services/GenreService.cs
> +
teveel whitespace

2019-11-19 15:20 UTC, NicoVermeir commented on Fletnix.Services/IGenreService.cs
> +
whitespace

2019-11-19 15:20 UTC, NicoVermeir commented on Fletnix/Messages/GenreCreatedMessage.cs
> +        public GenreCreatedMessage(Genre newGenre)
hier mag een whitespace voor komen

2019-11-19 15:20 UTC, NicoVermeir commented on Fletnix/ViewModel/CreateGenreViewModel.cs
> +
whitespace

2019-11-19 15:20 UTC, NicoVermeir commented on Fletnix/ViewModel/MainViewModel.cs
> +
teveel whitespace

2019-11-19 15:20 UTC, NicoVermeir commented on Fletnix/ViewModel/MainViewModel.cs
> +
teveel whitespace

2019-11-19 15:20 UTC, NicoVermeir commented on Fletnix/ViewModel/MainViewModel.cs
> +
teveel whitespace

2019-11-20 10:28 UTC, tdehaes commented
Nico,

ik denk dat ik iets fout gedaan heb bij het aanpassen van de code.
De bedoeling was om de bestaande pull request aan te passen, maar blijkbaar
is er een 2e pull request gemaakt.

Hoe moet ik nu verder om het juist te doen?

Thorsten

Op di 19 nov. 2019 om 16:20 schreef NicoVermeir <notifications@github.com>:

> *@NicoVermeir* requested changes on this pull request.
> ------------------------------
>
> In Fletnix.Repositories/GenreRepository.cs
> <https://github.com/NicoVermeir/Fletnix/pull/9#discussion_r347984815>:
>
> > +        public bool Create(Genre item)
>
> +        {
>
> +            try
>
> +            {
>
> +                var context = new FletnixContext();
>
> +                context.Genre.Add(item);
>
> +                context.SaveChanges();
>
> +
>
> +                return true;
>
> +            }
>
> +            catch (Exception)
>
> +            {
>
> +                return false;
>
> +
>
> +            }
>
> +
>
>
> Overbodige whitespace verwijderen
> ------------------------------
>
> In Fletnix.Repositories/GenreRepository.cs
> <https://github.com/NicoVermeir/Fletnix/pull/9#discussion_r347984930>:
>
> > +    class GenreRepository : IRepository<Genre>
>
> +    {
>
> +        public bool Create(Genre item)
>
> +        {
>
> +            try
>
> +            {
>
> +                var context = new FletnixContext();
>
> +                context.Genre.Add(item);
>
> +                context.SaveChanges();
>
> +
>
> +                return true;
>
> +            }
>
> +            catch (Exception)
>
> +            {
>
> +                return false;
>
> +
>
>
> overbodige whitespace
> ------------------------------
>
> In Fletnix.Services/GenreService.cs
> <https://github.com/NicoVermeir/Fletnix/pull/9#discussion_r347985161>:
>
> > @@ -0,0 +1,28 @@
>
> +﻿using System;
>
> +using System.Collections.Generic;
>
> +using System.Text;
>
> +using Fletnix.Model;
>
> +using Fletnix.Repositories;
>
> +
>
> +namespace Fletnix.Services
>
> +{
>
> +    class GenreService : IGenreService
>
> +    {
>
> +        private readonly IRepository<Genre> _genreRepository;
>
> +
>
>
> teveel whitespace
> ------------------------------
>
> In Fletnix.Services/IGenreService.cs
> <https://github.com/NicoVermeir/Fletnix/pull/9#discussion_r347985309>:
>
> > @@ -0,0 +1,15 @@
>
> +﻿using Fletnix.Model;
>
> +using System;
>
> +using System.Collections.Generic;
>
> +using System.Text;
>
> +
>
> +namespace Fletnix.Services
>
> +{
>
> +    public interface IGenreService
>
> +    {
>
> +        IList<Genre> GetGenres();
>
> +
>
> +        void SaveGenre(Genre item);
>
> +
>
>
> whitespace
> ------------------------------
>
> In Fletnix/Messages/GenreCreatedMessage.cs
> <https://github.com/NicoVermeir/Fletnix/pull/9#discussion_r347985469>:
>
> > @@ -0,0 +1,16 @@
>
> +﻿using Fletnix.Model;
>
> +using System;
>
> +using System.Collections.Generic;
>
> +using System.Text;
>
> +
>
> +namespace Fletnix.Messages
>
> +{
>
> +    public class GenreCreatedMessage
>
> +    {
>
> +        public Genre NewGenre { get; set; }
>
> +        public GenreCreatedMessage(Genre newGenre)
>
>
> hier mag een whitespace voor komen
> ------------------------------
>
> In Fletnix/ViewModel/CreateGenreViewModel.cs
> <https://github.com/NicoVermeir/Fletnix/pull/9#discussion_r347986172>:
>
> > +        public RelayCommand AddGenreCommand => _addGenreCommand ??= new RelayCommand(AddGenre);
>
> +
>
> +        public string Name
>
> +        {
>
> +            get => _name;
>
> +            set
>
> +            {
>
> +                _name = value;
>
> +            }
>
> +        }
>
> +
>
> +        public CreateGenreViewModel(IGenreService genreService)
>
> +        {
>
> +            _genreService = genreService;
>
> +            NewGenre = new Genre();
>
> +
>
>
> whitespace
> ------------------------------
>
> In Fletnix/ViewModel/MainViewModel.cs
> <https://github.com/NicoVermeir/Fletnix/pull/9#discussion_r347986432>:
>
> > @@ -56,18 +57,28 @@ public MainViewModel(ICatalogService catalogService)
>
>          {
>
>              _catalogService = catalogService;
>
>
>
> +
>
>
> teveel whitespace
> ------------------------------
>
> In Fletnix/ViewModel/MainViewModel.cs
> <https://github.com/NicoVermeir/Fletnix/pull/9#discussion_r347986492>:
>
> >              //Catalog = _catalogService.GetMovies().ToList();
>
>              Catalog = new ObservableCollection<CatalogItem>(catalog);
>
>
>
> +
>
>
> teveel whitespace
> ------------------------------
>
> In Fletnix/ViewModel/MainViewModel.cs
> <https://github.com/NicoVermeir/Fletnix/pull/9#discussion_r347986556>:
>
> >          private void OnCatalogItemCreated(CatalogItemCreatedMessage message)
>
>          {
>
>              Catalog.Add(message.NewCatalogItem);
>
>          }
>
>
>
> +
>
> +
>
>
> teveel whitespace
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NicoVermeir/Fletnix/pull/9?email_source=notifications&email_token=AKMMAHUPJR2ZVLKRWZDYKNLQUP74BA5CNFSM4JO2CG6KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCMCVH3Y#pullrequestreview-319116271>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKMMAHVC4BU2LWDOWRMQ67TQUP74BANCNFSM4JO2CG6A>
> .
>

2019-11-20 10:30 UTC, NicoVermeir commented
laat maar zo staan, mooi voorbeeld om maandag in de les te bekijken

2019-11-25 18:11 UTC, NicoVermeir approved these changes

2019-11-25 18:12 UTC, merged